from flask import Flask, request, jsonify
from flask_cors import CORS
from datetime import datetime
import hashlib
import time
import os
import re try: from pymongo import MongoClient HAS_MONGO = True
except ImportError: HAS_MONGO = False app = Flask(name)
CORS(app) MONGO_URI = os.environ.get(‘MONGO_URI’, ‘’)
DB_NAME = ‘task_cloud’
_memory_users = {}
_memory_tasks = {}
_mongo_client = None
_db = None def get_db(): global _mongo_client, _db if not HAS_MONGO or not MONGO_URI: return None if _mongo_client is None: try: _mongo_client = MongoClient(MONGO_URI, serverSelectionTimeoutMS=5000) _db = _mongo_client[DB_NAME] _db.users.find_one() except: return None return db def get_user(username): db = get_db() if db: doc = db.users.find_one({‘username’: username}) return {‘id’: doc[‘id’], ‘password’: doc[‘password’]} if doc else None return memory_users.get(username) def add_user(username, data): db = get_db() if db: db.users.insert_one({‘username’: username, **data}) else: memory_users[username] = data def get_user_by_id(user_id): db = get_db() if db: doc = db.users.find_one({‘id’: user_id}) return doc[‘username’] if doc else None for u, d in memory_users.items(): if d.get(‘id’) == user_id: return u return None def get_user_tasks(user_id): db = get_db() if db: doc = db.tasks.find_one({‘user_id’: user_id}) return {‘tasks’: doc.get(‘tasks’, []), ‘lastSync’: doc.get(‘lastSync’)} if doc else {‘tasks’: [], ‘lastSync’: None} return memory_tasks.get(user_id, {‘tasks’: [], ‘lastSync’: None}) def save_user_tasks(user_id, data): db = get_db() if db: db.tasks.update_one({‘user_id’: user_id}, {‘$set’: data}, upsert=True) else: memory_tasks[user_id] = data def hash_pwd(p): return hashlib.sha256(p.encode()).hexdigest() def gen_token(uid): t = int(time.time()) s = hashlib.md5(f"{uid}{t}key".encode()).hexdigest()[:16] return f"{uid}{t}{s}" def verify_token(tok): try: parts = tok.split('') uid = f"{parts[0]}{parts[1]}" if len(parts) >= 4 else None return uid if uid and get_user_by_id(uid) else None except: return None def get_uid(): auth = request.headers.get(‘Authorization’, ‘’) tok = auth.replace(‘Bearer ‘, ‘’) if auth.startswith(‘Bearer ‘) else auth return verify_token(tok) @app.route(’/api/health’)
def health(): return jsonify({‘status’: ‘ok’, ‘storage’: ‘mongodb’ if get_db() else ‘memory’, ‘time’: datetime.now().isoformat()}) @app.route(’/api/register’, methods=[‘POST’])
def register(): d = request.get_json() or {} u, p = d.get(‘username’, ‘’).strip(), d.get(‘password’, ‘’) if not u or not p: return jsonify({‘success’: False, ‘error’: ‘请填写用户名和密码’}), 400 if len(u) < 2 or len(u) > 20: return jsonify({‘success’: False, ‘error’: ‘用户名2-20字符’}), 400 if not re.match(r’^[a-zA-Z0-9\u4e00-\u9fa5]+$', u): return jsonify({‘success’: False, ‘error’: ‘用户名格式错误’}), 400 if get_user(u): return jsonify({‘success’: False, ‘error’: ‘用户名已存在’}), 400 uid = f"user{int(time.time() * 1000)}" add_user(u, {‘id’: uid, ‘password’: hash_pwd(p), ‘createdAt’: datetime.now().isoformat()}) save_user_tasks(uid, {‘tasks’: [], ‘lastSync’: None}) return jsonify({‘success’: True, ‘userId’: uid, ‘token’: gen_token(uid)}) @app.route(‘/api/login’, methods=[‘POST’])
def login(): d = request.get_json() or {} u, p = d.get(‘username’, ‘’).strip(), d.get(‘password’, ‘’) if not u or not p: return jsonify({‘success’: False, ‘error’: ‘请填写用户名和密码’}), 400 user = get_user(u) if not user or user[‘password’] != hash_pwd(p): return jsonify({‘success’: False, ‘error’: ‘用户名或密码错误’}), 401 return jsonify({‘success’: True, ‘userId’: user[‘id’], ‘token’: gen_token(user[‘id’])}) @app.route(‘/api/sync/upload’, methods=[‘POST’])
def upload(): uid = get_uid() if not uid: return jsonify({‘success’: False, ‘error’: ‘未授权’}), 401 tasks = request.get_json().get(‘tasks’, []) save_user_tasks(uid, {‘tasks’: tasks, ‘lastSync’: datetime.now().isoformat()}) return jsonify({‘success’: True, ‘taskCount’: len(tasks)}) @app.route(‘/api/sync/download’, methods=[‘POST’])
def download(): uid = get_uid() if not uid: return jsonify({‘success’: False, ‘error’: ‘未授权’}), 401 t = get_user_tasks(uid) return jsonify({‘success’: True, ‘tasks’: t[‘tasks’], ‘lastSync’: t[‘lastSync’]}) @app.route(‘/’)
def index(): return jsonify({‘service’: ‘Task Cloud’, ‘version’: ‘2.0’, ‘storage’: ‘mongodb’ if get_db() else ‘memory’}) if name == ‘main’: port = int(os.environ.get(‘PORT’, 8765)) app.run(host=‘0.0.0.0’, port=port, debug=False)
